-- H2 schema for DeskFlow (auto-run by Spring Boot)
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS desk;

CREATE TABLE desk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  floor INT NOT NULL,
  has_monitor BOOLEAN NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_desk_code UNIQUE (code),
  CONSTRAINT chk_desk_code_not_blank CHECK (CHAR_LENGTH(TRIM(code)) > 0),
  CONSTRAINT chk_floor_positive CHECK (floor > 0)
);

CREATE TABLE booking (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  desk_id BIGINT NOT NULL,
  employee_name VARCHAR(120) NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_booking_desk
    FOREIGN KEY (desk_id) REFERENCES desk(id)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT,
  -- Core business rule: one booking per desk per date
  CONSTRAINT uq_booking_desk_date UNIQUE (desk_id, date),
  CONSTRAINT chk_booking_employee_name_not_blank CHECK (CHAR_LENGTH(TRIM(employee_name)) > 0)
);

CREATE INDEX idx_desk_floor_monitor_active ON desk (floor, has_monitor, is_active);
CREATE INDEX idx_booking_date ON booking (date);
